class FMCMainDisplayDebug {
    static GenerateDebugInput() {
        for (let i = 0; i < 6; i++) {
            let buttonLeft = document.createElement("input");
            buttonLeft.id = "input-" + i + "-left";
            buttonLeft.type = "button";
            buttonLeft.style.position = "absolute";
            buttonLeft.style.left = "20px";
            buttonLeft.style.top = (102 + i * 43) + "px";
            buttonLeft.style.width = "22px";
            buttonLeft.style.height = "14px";
            document.body.appendChild(buttonLeft);
            let buttonRight = document.createElement("input");
            buttonRight.id = "input-" + i + "-right";
            buttonRight.type = "button";
            buttonRight.style.position = "absolute";
            buttonRight.style.left = "410px";
            buttonRight.style.top = (102 + i * 43) + "px";
            buttonRight.style.width = "22px";
            buttonRight.style.height = "14px";
            document.body.appendChild(buttonRight);
        }
        let btnInit = document.createElement("input");
        btnInit.value = "INIT REF";
        btnInit.id = "input-initref";
        btnInit.type = "button";
        btnInit.style.position = "absolute";
        btnInit.style.left = "60px";
        btnInit.style.top = "380px";
        btnInit.style.width = "42px";
        btnInit.style.height = "24px";
        btnInit.style.padding = "0px";
        btnInit.style.fontSize = "8px";
        document.body.appendChild(btnInit);
        let btnRTE = document.createElement("input");
        btnRTE.value = "RTE";
        btnRTE.id = "input-rte";
        btnRTE.type = "button";
        btnRTE.style.position = "absolute";
        btnRTE.style.left = "110px";
        btnRTE.style.top = "380px";
        btnRTE.style.width = "42px";
        btnRTE.style.height = "24px";
        btnRTE.style.padding = "0px";
        btnRTE.style.fontSize = "8px";
        document.body.appendChild(btnRTE);
        let btnDepArr = document.createElement("input");
        btnDepArr.value = "DEP ARR";
        btnDepArr.id = "input-deparr";
        btnDepArr.type = "button";
        btnDepArr.style.position = "absolute";
        btnDepArr.style.left = "160px";
        btnDepArr.style.top = "380px";
        btnDepArr.style.width = "42px";
        btnDepArr.style.height = "24px";
        btnDepArr.style.padding = "0px";
        btnDepArr.style.fontSize = "8px";
        document.body.appendChild(btnDepArr);
        let btnATC = document.createElement("input");
        btnATC.value = "ATC";
        btnATC.id = "input-atc";
        btnATC.type = "button";
        btnATC.style.position = "absolute";
        btnATC.style.left = "210px";
        btnATC.style.top = "380px";
        btnATC.style.width = "42px";
        btnATC.style.height = "24px";
        btnATC.style.padding = "0px";
        btnATC.style.fontSize = "8px";
        document.body.appendChild(btnATC);
        let btnFix = document.createElement("input");
        btnFix.value = "FIX";
        btnFix.id = "input-fix";
        btnFix.type = "button";
        btnFix.style.position = "absolute";
        btnFix.style.left = "60px";
        btnFix.style.top = "410px";
        btnFix.style.width = "42px";
        btnFix.style.height = "24px";
        btnFix.style.padding = "0px";
        btnFix.style.fontSize = "8px";
        document.body.appendChild(btnFix);
        let btnLegs = document.createElement("input");
        btnLegs.value = "LEGS";
        btnLegs.id = "input-legs";
        btnLegs.type = "button";
        btnLegs.style.position = "absolute";
        btnLegs.style.left = "110px";
        btnLegs.style.top = "410px";
        btnLegs.style.width = "42px";
        btnLegs.style.height = "24px";
        btnLegs.style.padding = "0px";
        btnLegs.style.fontSize = "8px";
        document.body.appendChild(btnLegs);
        let btnHold = document.createElement("input");
        btnHold.value = "HOLD";
        btnHold.id = "input-hold";
        btnHold.type = "button";
        btnHold.style.position = "absolute";
        btnHold.style.left = "160px";
        btnHold.style.top = "410px";
        btnHold.style.width = "42px";
        btnHold.style.height = "24px";
        btnHold.style.padding = "0px";
        btnHold.style.fontSize = "8px";
        document.body.appendChild(btnHold);
        let btnFmcComm = document.createElement("input");
        btnFmcComm.value = "FMC COMM";
        btnFmcComm.id = "input-fmccomm";
        btnFmcComm.type = "button";
        btnFmcComm.style.position = "absolute";
        btnFmcComm.style.left = "210px";
        btnFmcComm.style.top = "410px";
        btnFmcComm.style.width = "42px";
        btnFmcComm.style.height = "24px";
        btnFmcComm.style.padding = "0px";
        btnFmcComm.style.fontSize = "8px";
        document.body.appendChild(btnFmcComm);
        let btnProg = document.createElement("input");
        btnProg.value = "PROG";
        btnProg.id = "input-prog";
        btnProg.type = "button";
        btnProg.style.position = "absolute";
        btnProg.style.left = "260px";
        btnProg.style.top = "410px";
        btnProg.style.width = "42px";
        btnProg.style.height = "24px";
        btnProg.style.padding = "0px";
        btnProg.style.fontSize = "8px";
        document.body.appendChild(btnProg);
        let btnExec = document.createElement("input");
        btnExec.value = "EXEC";
        btnExec.id = "input-exec";
        btnExec.type = "button";
        btnExec.style.position = "absolute";
        btnExec.style.left = "310px";
        btnExec.style.top = "410px";
        btnExec.style.width = "42px";
        btnExec.style.height = "24px";
        btnExec.style.padding = "0px";
        btnExec.style.fontSize = "8px";
        document.body.appendChild(btnExec);
        let btnMenu = document.createElement("input");
        btnMenu.value = "MENU";
        btnMenu.id = "input-menu";
        btnMenu.type = "button";
        btnMenu.style.position = "absolute";
        btnMenu.style.left = "60px";
        btnMenu.style.top = "440px";
        btnMenu.style.width = "42px";
        btnMenu.style.height = "24px";
        btnMenu.style.padding = "0px";
        btnMenu.style.fontSize = "8px";
        document.body.appendChild(btnMenu);
        let btnNavRad = document.createElement("input");
        btnNavRad.value = "NAV RAD";
        btnNavRad.id = "input-navrad";
        btnNavRad.type = "button";
        btnNavRad.style.position = "absolute";
        btnNavRad.style.left = "110px";
        btnNavRad.style.top = "440px";
        btnNavRad.style.width = "42px";
        btnNavRad.style.height = "24px";
        btnNavRad.style.padding = "0px";
        btnNavRad.style.fontSize = "8px";
        document.body.appendChild(btnNavRad);
        let btnPrevPage = document.createElement("input");
        btnPrevPage.value = "PREV PAGE";
        btnPrevPage.id = "input-prevpage";
        btnPrevPage.type = "button";
        btnPrevPage.style.position = "absolute";
        btnPrevPage.style.left = "60px";
        btnPrevPage.style.top = "470px";
        btnPrevPage.style.width = "42px";
        btnPrevPage.style.height = "24px";
        btnPrevPage.style.padding = "0px";
        btnPrevPage.style.fontSize = "8px";
        document.body.appendChild(btnPrevPage);
        let btnNextPage = document.createElement("input");
        btnNextPage.value = "NEXT PAGE";
        btnNextPage.id = "input-nextpage";
        btnNextPage.type = "button";
        btnNextPage.style.position = "absolute";
        btnNextPage.style.left = "110px";
        btnNextPage.style.top = "470px";
        btnNextPage.style.width = "42px";
        btnNextPage.style.height = "24px";
        btnNextPage.style.padding = "0px";
        btnNextPage.style.fontSize = "8px";
        document.body.appendChild(btnNextPage);
        let alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        for (let i = 0; i < 26; i++) {
            let letter = alphabet[i];
            let buttonLetter = document.createElement("input");
            buttonLetter.value = letter;
            buttonLetter.id = "input-letter-" + letter;
            buttonLetter.type = "button";
            buttonLetter.style.position = "absolute";
            buttonLetter.style.left = (180 + (i % 5) * 30) + "px";
            buttonLetter.style.top = (440 + Math.floor(i / 5) * 30) + "px";
            buttonLetter.style.width = "24px";
            buttonLetter.style.height = "24px";
            buttonLetter.style.padding = "0px";
            buttonLetter.style.fontSize = "8px";
            document.body.appendChild(buttonLetter);
        }
        let btnSpace = document.createElement("input");
        btnSpace.value = "SP";
        btnSpace.id = "input-space";
        btnSpace.type = "button";
        btnSpace.style.position = "absolute";
        btnSpace.style.left = "210px";
        btnSpace.style.top = "590px";
        btnSpace.style.width = "24px";
        btnSpace.style.height = "24px";
        btnSpace.style.padding = "0px";
        btnSpace.style.fontSize = "8px";
        document.body.appendChild(btnSpace);
        let btnDel = document.createElement("input");
        btnDel.value = "DEL";
        btnDel.id = "input-delete";
        btnDel.type = "button";
        btnDel.style.position = "absolute";
        btnDel.style.left = "240px";
        btnDel.style.top = "590px";
        btnDel.style.width = "24px";
        btnDel.style.height = "24px";
        btnDel.style.padding = "0px";
        btnDel.style.fontSize = "8px";
        document.body.appendChild(btnDel);
        let btnDiv = document.createElement("input");
        btnDiv.value = "/";
        btnDiv.id = "input-div";
        btnDiv.type = "button";
        btnDiv.style.position = "absolute";
        btnDiv.style.left = "270px";
        btnDiv.style.top = "590px";
        btnDiv.style.width = "24px";
        btnDiv.style.height = "24px";
        btnDiv.style.padding = "0px";
        btnDiv.style.fontSize = "8px";
        document.body.appendChild(btnDiv);
        let btnClr = document.createElement("input");
        btnClr.value = "CLR";
        btnClr.id = "input-clr";
        btnClr.type = "button";
        btnClr.style.position = "absolute";
        btnClr.style.left = "300px";
        btnClr.style.top = "590px";
        btnClr.style.width = "24px";
        btnClr.style.height = "24px";
        btnClr.style.padding = "0px";
        btnClr.style.fontSize = "8px";
        document.body.appendChild(btnClr);
        for (let i = 1; i <= 9; i++) {
            let buttonNumber = document.createElement("input");
            buttonNumber.value = i + "";
            buttonNumber.id = "input-number-" + i;
            buttonNumber.type = "button";
            buttonNumber.style.position = "absolute";
            buttonNumber.style.left = (90 + ((i - 1) % 3) * 30) + "px";
            buttonNumber.style.top = (500 + Math.floor((i - 1) / 3) * 30) + "px";
            buttonNumber.style.width = "24px";
            buttonNumber.style.height = "24px";
            buttonNumber.style.padding = "0px";
            buttonNumber.style.fontSize = "8px";
            document.body.appendChild(buttonNumber);
        }
        let buttonZero = document.createElement("input");
        buttonZero.value = "0";
        buttonZero.id = "input-number-0";
        buttonZero.type = "button";
        buttonZero.style.position = "absolute";
        buttonZero.style.left = "120px";
        buttonZero.style.top = "590px";
        buttonZero.style.width = "24px";
        buttonZero.style.height = "24px";
        buttonZero.style.padding = "0px";
        buttonZero.style.fontSize = "8px";
        document.body.appendChild(buttonZero);
    }
}
FMCMainDisplayDebug.MasterData = {
    planeModel: "747",
    engineReference: "B1G-3NG1N3",
    navData: "FROM SIM",
    active: "TODAY",
    opProgram: "v1.0"
};
//# sourceMappingURL=B747_8_FMC_MainDisplayDebug.js.map